# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: auto-update-generated-data

on:
  push:
    branches: [ "main" ]

jobs:
  update-generated-file:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    defaults:
      run:
        working-directory: 'development/backend/src'

    steps:
      - name: setup environment for git
        uses: actions/checkout@v3

      - name: setup environemnt for node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'development/backend/package-lock.json'

      - name: setup environment for project
        run: npm i && npm i -g ts-node

      - name: generate and validate properties data
        run: |
          ts-node genPropertiesFromReadme.ts  # 生成停贷数据（同时生成tree与flat）
          ts-node validateLocalImages.ts      # 验证本地图片索引
          ts-node genMdFromPropertiesTree.ts  # tree --> 新的readme

      - name: check for changes
        run: |
          if git diff --exit-code; then
            echo "has_changes=false" >> $GITHUB_ENV
          else
            echo "has_changes=true" >> $GITHUB_ENV
          fi

      - name: regenerate map if local changes detected
        if: ${{ env.has_changes == 'true' }}
        run: |
          cd visualization
          ts-node genCitie.ts         # flat --> 城市数据
          ts-node genMap.ts -t all    # 城市数据 --> 地图

      - name: commit and pr if local changes detected
        if: ${{ env.has_changes == 'true' }}
        uses: peter-evans/create-pull-request@v4
        with:
          add-paths: |
            data/generated/*
          commit-message: "Update generated data"
          title: 'Update generated data'
          body: 'Auto update the the generated data'
          labels: automated-pr
          branch: automated/update-generated-data
          delete-branch: true
